### UI ###
[xp_tracker.border.inner]
color=0x4d4d4d
opacity=0

[xp_tracker.border.outer]
color=0x000000
opacity=0

[rune_pouch.border.inner]
color=0x595959
opacity=100

[rune_pouch.border.outer]
color=0x383838
opacity=100

[spell_tooltip.border.inner]
color=0x595959
opacity=0

[spell_tooltip.border.outer]
color=0x383838
opacity=0

### Chatbox ###
[chatbox.separator]
color=0x000000

[chatbox.separator.opaque]
opacity=0

[chatbox.separator.transparent]
opacity=200

[achievement_diary.entry.border]
color=0x3f3f3f
opacity=150

### Tabs ###
[account_management.separator]
color=0x3f3f3f

[settings_tab.separator]
color=0x3f3f3f

[quest_tab.separator]
color=0x3f3f3f

[channel_tab.separator]
color=0x3f3f3f

[world_switcher.border.bottom]
color=0x3f3f3f
opacity=50

[world_switcher.border.top]
color=0x3f3f3f
opacity=50

[world_switcher.window.border.inner]
color=0x3f3f3f
opacity=0

[world_switcher.window.border.outer]
color=0x3f3f3f
opacity=0

### GE & Bank ###
[ge.inventory.glow]
color=0x999999

[ge.slot.border.inner]
color=0x595959
opacity=0

[ge.slot.border.outer]
color=0x383838
opacity=0

[ge.offer.border.inner]
color=0x595959
opacity=0

[ge.offer.border.outer]
color=0x383838
opacity=0

[bank.menu.border.inner.fillers]
color=0xe0e0c
opacity=0

[bank.menu.border.outer.fillers]
color=0x3f3f3f
opacity=0

[bank.inventory.locked]
color=0x5b5b5b
opacity=0

[bank.inventory.rune_pouch.border.inner]
color=0x595959
opacity=0

[bank.inventory.rune_pouch.border.outer]
color=0x383838
opacity=0

### Combat Achivements ###
[combat_achievements.rewards.body.border.inner]
color=0x595959
opacity=0

[combat_achievements.rewards.body.border.outer]
color=0x383838
opacity=0

[combat_achievements.rewards.section.border.inner]
color=0x595959
opacity=0

[combat_achievements.rewards.section.border.outer]
color=0x383838
opacity=0

[combat_achievements.boss.border.inner]
color=0x595959
opacity=0

[combat_achievements.boss.border.outer]
color=0x383838
opacity=0

### Collection Log ###
[collection_log.border]
color=0x383838

### Skill Guide ###
[skill_guide.body.border.inner]
color=0x595959
opacity=0

[skill_guide.body.border.outer]
color=0x383838
opacity=0

[skill_guide.tab.border]
color=0x383838
opacity=0